### ISSUE TITLE
BUG: No identification of nested classes in stack trace in Extractor

### ISSUE THREAD

**Issue by mdoron** [TechnionYP5777/Bugquery#132]
Stack trace for example: 
```
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at B$C.<init>(B.java:9)
	at B.<init>(B.java:4)
	at A.<init>(A.java:4)
	at main.main(main.java:5)
```
then we don't find line 9 in B.java.

**Comment by mdoron** [comment]
the problem is that we use hashmap without a list what make putting two markers on same file impossible. fixing now.

**Comment by mdoron** [comment]
Done
