### ISSUE TITLE
Fix Raviv's Bug

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#158]
Raviv submitted a bug for our website, in this issue we will track it's fixing progress.

java.lang.NullPointerException
 at org.eclipse.oomph.setup.ui.SetupUIPlugin.performStartup(SetupUIPlugin.java:443)
 at org.eclipse.oomph.setup.ui.SetupUIPlugin.access$5(SetupUIPlugin.java:414)
 at org.eclipse.oomph.setup.ui.SetupUIPlugin$1$1.run(SetupUIPlugin.java:253)
 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by yosefraisman** [comment]
So far, narrowed down the problem, and also found out that adding `Exception in thread "main"` to the input's start makes it run okay. I suspect the bug has to do with the trace extraction. Will update when I make further progress.

**Comment by yosefraisman** [comment]
Problem was, as per usual, carriage return.
